Repository FRONTENDBOOTCAMP-13th/EagleSauce, pull requests merged in 2025-03, with the labels that each got.

#12 💄style : style.css/root설정
  .gitignore
  src/style.css
Labels: 🎨Html/CSS

#14 💄style : componen-build
  index.html
  src/components/main-banner.html
  src/components/main-bottle.html
  src/components/main-footer.html
  src/components/main-header.html
  vite.config.js
Labels: 🎨Html/CSS

#19 💄style: 1차 main-banner.html
  src/components/main-banner.html
Labels: 🎨Html/CSS

#23 💄style : 헤더작업마무리
  public/assets/images/napoli-li.jpg
  public/assets/images/shop-all2.webp
  src/components/main-header.html
  src/style.css
Labels: 🎨Html/CSS

#25 :lipstick:style: 메인페이지 배너영역 수정
  src/components/main-bottle.html
  src/style.css
Labels: 🎨Html/CSS

#26 💄style: 메인페이지 헤더/배너영역 수정
  public/assets/images/3b216110d51cb6705e7fa96281a0e8f2.gif
  public/assets/images/53451e197765b700c21b38bc44dae0c7 (1).png
  public/assets/images/PARMESANGOCHUJANG-nametag.png
  public/assets/images/PYOGORUFFLE-nametag.png
  public/assets/images/XOSHRIMP-nametag.png
  public/assets/images/rolltxt1.png
  src/components/main-bottle.html
  src/components/main-header.html
  src/style.css
Labels: 🎨Html/CSS

#24 📝 docs: README에 내용 추가
  README.md
Labels: 📜Docs

#33 💄style: about/ourbrand페이지 설정
  src/pages/about-ourbrand.html
  src/pages/about-ourbrand01.html
  src/pages/about-ourbrand02.html
  src/style.css
Labels: 🎨Html/CSS

#51 Feat/commu review
  index.html
  public/assets/icon/first.svg
  public/assets/icon/last.svg
  public/assets/icon/next.svg
  public/assets/icon/previous.svg
  public/assets/icon/star_black.svg
  public/assets/images/img-item.png
  public/assets/images/review-con-1.png
  public/assets/images/review-con-4.jpg
  public/assets/images/review-con-5.jpg
  public/assets/images/shrimp.png
  public/assets/images/symbol.png
  src/components/about-nametag.html
  src/components/community-reviewimg.html
  src/components/community-reviewitem.html
  src/components/community-reviewtext.html
  src/components/community-reviewtitle.html
  src/pages/community-review.html
  src/style.css
  vite.config.js
Labels: 🎨Html/CSS

#52 :lipstick:style Add Community event page
  src/pages/community-event.html
  src/style.css
Labels: 🎨코드구현

#56 :lipstick:style: 카트 페이지 제작
  index.html
  src/pages/cart.html
  src/style.css
Labels: 🎨코드구현

#55 💄style: community-faq제작
  public/assets/images/nutrition.png
  src/components/community-pagination2.html
  src/components/faq-summary.html
  src/components/search-bar.html
  src/pages/community-faq.html
  src/pages/community-review.html
Labels: 🎨코드구현

#71 💄style : Community-Q&A 페이지제작
  index.html
  public/assets/images/qna-bg.png
  public/assets/images/qna-phone.png
  src/pages/cart.html
  src/pages/community-qna.html
Labels: 🎨코드구현

#73 :lipstick:style: Shop-section13 파일 제작
  public/assets/images/MichelinStar.png
  src/components/shop-section13.html
  src/pages/cart.html
Labels: 🎨코드구현

#74 💄style : community-napolimatfia/layout 중간커밋
  public/assets/images/coupon-1.png
  public/assets/images/coupon-2.png
  public/assets/images/coupon-3.png
  public/assets/images/sec1-bg.png
  public/assets/images/shrimp.png
  src/pages/community-napolimatfia.html
  src/style.css
Labels: 🎨코드구현

#77 :lipstick:style shop-section12 중간 커밋
  src/components/shop-section12.html
  src/components/shop-section13.html
Labels: 🎨코드구현

#76 💄style : section-01 중간커밋
  public/assets/images/npay_btn_mo.png
  public/assets/images/spicy2.png
  src/components/select-option.html
  src/components/shop-section01.html
  src/style.css
Labels: 🎨코드구현

#82 💄style : section-05 완성
  public/assets/images/sec1.jpg
  src/components/shop-section05.html
Labels: 🎨코드구현

#83 💄style : section-06 완성
  public/assets/images/sec5-slide-pyogo.png
  src/components/shop-section06.html
  src/style.css
Labels: 🎨코드구현

#84 :lipstick:style: shop section-11 제작
  src/components/shop-section11.html
Labels: 🎨코드구현

#85 💄style : section-09 완성
  public/assets/images/noise.png
  public/assets/images/sec8-graph-1.png
  src/components/shop-section09.html
  src/style.css
Labels: 🎨코드구현

#86 💄style: shop-pyogoruffle-section-04번
  src/components/shop-section04.html
  src/style.css
Labels: 🎨코드구현

#95 💄style : pyogo기본페이지세팅
  index.html
  src/components/shop-section03.html
  src/pages/shop-hotnkit.html
  src/pages/shop-parmesan.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
  src/style.css
Labels: 🎨코드구현

#96 :lipstick:style: shop-pyogoruffle 움직이는 텍스트 추가페이지세팅
  src/pages/shop-pyogo.html
Labels: 🎨코드구현

#99 💄style : shop/pyogoruffle완성
  src/pages/shop-pyogo.html
Labels: 🎨코드구현

#104 🛠️ build : package.json 추가설정
  package.json
Labels: ⚙️환경세팅

#103 :recycle:refactor: refactoring shop-section-10~11
  src/pages/shop-pyogo.html
Labels: 🛠️코드수정

#105 ♻️refactor : section2-코드리팩토링
  src/components/shop-section02.html
Labels: 🛠️코드수정

#106 ♻️refactor: shop-section03 코드 리팩토링 완성
  public/assets/images/section-03.jpg
  src/components/shop-section03.html
  src/style.css
Labels: 🛠️코드수정

#108 💄style : [shop] all products / header,footer
  public/assets/images/icon_best.jpg
  src/components/shop-detail_view.html
  src/components/shop-product_item.html
  src/js/footer.js
  src/js/header.js
  src/main.js
  src/pages/shop-all_products.html
  src/style.css
Labels: ✨ 기능개발, 🎨코드구현

#112 ♻️refactor: shop-section01 코드 리팩토링
  src/components/shop-section01.html
Labels: 🛠️코드수정

#113 110 shop productsection 13 refactor 코드수정 코드리팩토링
  src/components/shop-section13.html
Labels: 🛠️코드수정

#115 ♻️refactor: shop-section02 코드 리팩토링
  src/components/shop-section02.html
Labels: 🛠️코드수정

#119 ♻️refactor: shop-section05 코드 리팩토링
  src/components/shop-section05.html
Labels: 🛠️코드수정

#121 :recycle:refactor: shop-productsection-12 코드 리펙토링
  src/components/shop-section12.html
  src/components/shop-section13.html
Labels: 🛠️코드수정

#123 ♻️refactor: shop-section06 코드 리팩토링
  src/components/shop-section06.html
Labels: 🛠️코드수정

#129 ♻️refactor: shop-section03 코드 리팩토링
  src/components/shop-section03.html
Labels: 🛠️코드수정

#127 ♻️refactor: shop-section09 코드 리팩토링
  src/components/shop-section09.html
Labels: 🛠️코드수정

#125 ♻️refactor: shop-section08 코드 리팩토링
  src/components/shop-section08.html
Labels: 🛠️코드수정

#133 ♻️refactor: shop-all products 코드 리팩토링
  src/pages/community-napolimatfia.html
  src/pages/shop-all_products.html
  src/pages/shop-giftbag.html
Labels: 🛠️코드수정

#135 ♻️refactor: shop-section12
  src/components/shop-section12.html
Labels: 🛠️코드수정

#142 :recycle:refactor: shop-section11 코드 리펙토링
  src/components/shop-section11.html
Labels: 🛠️코드수정

#143 ♻️refactor: shop-section04 코드 리펙토링 완성
  src/components/shop-section04.html
  src/style.css
Labels: 🛠️코드수정

#145 Shop/pyogoruffle psy
  src/components/shop-section04.html
  src/pages/shop-pyogo.html
Labels: 🛠️코드수정

#146 ♻️refactor: [COMMUNITY] napolimatfia/refactor
  src/pages/community-napolimatfia.html
  src/pages/shop-all_products.html
Labels: 🛠️코드수정

#148 :recycle: refactor: [COMMUMITY] napolimatfia/refactor 링크연결
  src/pages/community-napolimatfia.html
Labels: 🛠️코드수정

#149 💄style : shop/Hotnkit완성
  public/assets/images/section-03all.jpg
  src/pages/shop-hotnkit.html
  src/pages/shop-pyogo.html
  src/style.css
Labels: 🎨코드구현

#152 ♻️refactor : our-brand
  src/pages/about-ourbrand.html
Labels: 🛠️코드수정

#156 Event/refactor psy
  public/assets/images/kakao-event.jpg
  public/assets/images/kakao-event2.jpg
  public/assets/images/kakao-event3.jpg
  src/pages/community-event.html
  src/pages/community-eventboard.html
Labels: 🎨코드구현, 🛠️코드수정

#150 :lipstick:style: shop-parmesan 페이지 제작완료
  public/assets/images/parmesan_1.png
  public/assets/images/parmesan_2.png
  public/assets/images/scroll1-2.png
  public/assets/images/scroll2-2.png
  public/assets/images/sec8-graph-2.png
  src/pages/shop-parmesan.html
  src/style.css
Labels: 🎨코드구현

#159 💄style: shop-XO-Shrimp 페이지 완성
  assets/images/point-bg.png
  public/assets/images/XO-section5.jpg
  public/assets/images/XO-section6.png
  public/assets/images/XO-section8(2).png
  public/assets/images/XO-section8.png
  src/pages/shop-shrimp.html
Labels: 🎨코드구현

#163 :recycle:refactor community-faq 코드 리펙토링
  src/pages/about-inquiry.html
  src/pages/community-faq.html
Labels: 🛠️코드수정

#168 ♻️refactor : event2
  src/pages/community-event.html
  src/pages/community-eventboard.html
  src/pages/community-napolimatfia.html
Labels: 🛠️코드수정

#170 ♻️refactor : Header/refactor psy
  src/components/main-header.html
  src/js/header.js
Labels: 🐞버그수정, 🛠️코드수정

#172 :recycle:refacotr: extra-search 코드 리펙토링
  src/pages/community-faq.html
  src/pages/search.html
  src/style.css
Labels: 🛠️코드수정

#173 :pencil: rename: header, footer 컴포넌트화
  src/js/footer.js
  src/js/header.js
  src/js/main-header.js
  src/js/sub-header.js
  src/main.js
  src/pages/community-napolimatfia.html
  src/pages/home.html
Labels: 🛠️코드수정

#176 :recycle:refactor: extra-cart 코드 리펙토링
  src/pages/cart.html
Labels: 🛠️코드수정

#179 ♻️refactor : search refactor
  src/pages/search.html
Labels: 🛠️코드수정

#180 :recycle:refactor community-napolimatfia 코드 리펙토링
  src/pages/about-inquiry.html
  src/pages/cart.html
  src/pages/community-napolimatfia.html
  src/pages/home.html
Labels: 🛠️코드수정

#182 ♻️refactor: community-review-refactor
  assets/images/review-con-1.png
  src/pages/community-review.html
Labels: 🛠️코드수정

#186 ♻️refactor: all page repactor
  public/assets/images/3-4.jpg
  public/assets/images/favicon.png
  src/js/main-header.js
  src/main.js
  src/pages/about-inquiry.html
  src/pages/about-ourbrand.html
  src/pages/cart.html
  src/pages/community-event.html
  src/pages/community-eventboard.html
  src/pages/community-faq.html
  src/pages/community-napolimatfia.html
  src/pages/community-qna.html
  src/pages/community-recipes_and_paring.html
  src/pages/community-review.html
  src/pages/home.html
  src/pages/join-login.html
  src/pages/search.html
  src/pages/shop-all_products.html
  src/pages/shop-giftbag.html
  src/pages/shop-hotnkit.html
  src/pages/shop-parmesan.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
  src/style.css
Labels: 🐞버그수정, 🛠️코드수정

#188 ♻️refactor: all page head
  src/main.js
  src/pages/about-inquiry.html
  src/pages/about-ourbrand.html
  src/pages/cart.html
  src/pages/community-event.html
  src/pages/community-eventboard.html
  src/pages/community-faq.html
  src/pages/community-napolimatfia.html
  src/pages/community-qna.html
  src/pages/community-recipes_and_paring.html
  src/pages/community-review.html
  src/pages/home.html
  src/pages/join-login.html
  src/pages/search.html
  src/pages/shop-all_products.html
  src/pages/shop-giftbag.html
  src/pages/shop-hotnkit.html
  src/pages/shop-parmesan.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
  src/style.css
Labels: 🛠️코드수정

#192 💄style : index2-component페이지관련
  src/components/community-reviewtext.html
  src/pages/index_2.html
Labels: 🎨코드구현

#194 :lipstick:style: shop-giftbag 페이지 제작
  public/assets/images/bag-size.jpg
  public/assets/images/giftsec-bg.jpg
  public/assets/images/giftsec1.jpg
  public/assets/images/giftsec2.jpg
  public/assets/images/giftsec3.jpg
  public/assets/images/sec2-2.jpg
  public/assets/images/sec2-bg.png
  public/assets/images/sec2-bottom.png
  src/pages/shop-giftbag.html
  src/style.css
Labels: 🎨코드구현

#195 ♻️refactor : refactor-bag
  src/pages/shop-giftbag.html
Labels: 🛠️코드수정

#197 ♻️refactor: component pages repactor / index page
  index.html
  src/components/common-footer.html
  src/components/community-napolimatfia-buynow.html
  src/components/community-napolimatfia-hashtag.html
  src/components/community-pagination.html
  src/components/community-pagination2.html
  src/components/community-recipes-paring-vedio.html
  src/components/community-review_img.html
  src/components/community-review_text.html
  src/components/community-reviewall.html
  src/components/community-reviewitem.html
  src/components/faq-summary.html
  src/components/main-banner.html
  src/components/main-bottle.html
  src/components/main-header.html
  src/components/main-photoframe.html
  src/components/main-showcase.html
  src/components/pages-btn.html
  src/components/pages-text.html
  src/components/search-bar.html
  src/components/shop-component_btn.html
  src/components/shop-component_info.html
  src/components/shop-component_select.html
  src/components/shop-component_taste.html
  src/components/shop-detail_view.html
  src/components/shop-product_item.html
  src/components/shop-section01.html
  src/components/shop-section02.html
  src/components/shop-section03.html
  src/components/shop-section04.html
  src/components/shop-section05.html
  src/components/shop-section06.html
  src/components/shop-section07.html
  src/components/shop-section08.html
  src/components/shop-section09.html
  src/components/shop-section10.html
  src/components/shop-section11.html
  src/components/shop-section12.html
  src/components/shop-section13.html
  src/main.js
  src/pages/community-napolimatfia.html
  src/pages/index_2.html
  src/pages/shop-all_products.html
  src/style.css
Labels: 🛠️코드수정

#199 :recycle: refactor: all page repactor
  index.html
  public/assets/images/kjo.png
  public/assets/images/loading.gif
  public/assets/images/pjh.png
  public/assets/images/psh.png
  public/assets/images/psy.png
  src/components/community-napolimatfia-hashtag.html
  src/components/community-pagination.html
  src/components/community-pagination2.html
  src/components/community-recipes-paring-vedio.html
  src/components/community-reviewall.html
  src/components/community-reviewimg.html
  src/components/community-reviewitem.html
  src/components/pages-text.html
  src/components/shop-component_info.html
  src/components/shop-component_select.html
  src/js/main-header.js
  src/main.js
  src/pages/about-inquiry.html
  src/pages/about-ourbrand.html
  src/pages/cart.html
  src/pages/community-event.html
  src/pages/community-eventboard.html
  src/pages/community-faq.html
  src/pages/community-napolimatfia.html
  src/pages/community-qna.html
  src/pages/community-recipes_and_paring.html
  src/pages/community-review.html
  src/pages/home.html
  src/pages/index_2.html
  src/pages/join-login.html
  src/pages/search.html
  src/pages/shop-all_products.html
  src/pages/shop-giftbag.html
  src/pages/shop-hotnkit.html
  src/pages/shop-parmesan.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
  src/style.css
Labels: 🛠️코드수정

#200 💄style : component-pages.html
  index.html
  src/components/community-recipes-paring-vedio.html
  src/components/community-recipes_item.html
  src/components/pages-pagination.html
  src/components/pages-pagination2.html
  src/components/pages-searchbar.html
  src/components/pages-select.html
Labels: 🐞버그수정, 🎨코드구현, 🛠️코드수정

#203 💄style : index페이지연결 컴포넌트 정리
  index.html
  src/components/common-footer.html
  src/components/community-napolimatfia-buynow.html
  src/components/community-napolimatfia-hashtag.html
  src/components/community-review_all.html
  src/components/community-review_item.html
  src/components/community-review_text.html
  src/components/community-reviewall.html
  src/components/community-reviewimg.html
  src/components/community-reviewitem.html
  src/components/faq-summary.html
  src/components/main-footer.html
  src/components/pages-btn.html
  src/components/pages-pagination.html
  src/components/pages-pagination2.html
  src/components/pages-searchbar.html
  src/components/pages-select.html
  src/components/pages-summary.html
  src/components/pages-tag.html
  src/components/pages-text.html
  src/components/shop-component_btn.html
  src/components/shop-component_info.html
  src/components/shop-component_taste.html
  src/components/shop-product_item.html
  src/components/shop-product_item2.html
  src/components/shop-product_item3.html
Labels: 🎨코드구현

#205 💄style : stylecss추가
  index.html
  src/style.css
Labels: 🎨코드구현

#206 Index/mobile content psy
  index.html
  public/assets/images/phone-screen1.png
  public/assets/images/phone-screen2.png
  public/assets/images/phone-screen3.png
  public/assets/images/phone-screen4.png
  public/assets/images/screenshot2.png
  src/components/main-header.html
  src/js/main-header.js
  src/js/sub-header.js
  src/main.js
  src/pages/shop-parmesan.html
  src/pages/shop-shrimp.html
Labels: 🎨코드구현

#208 ♻️refactor: footer 이미지 수정
  src/components/pages-tag.html
  src/js/footer.js
  src/style.css
Labels: 🛠️코드수정

#209 🐛 bug : 배포 시 이미지 경로 문제 재설정
  src/components/main-header.html
  src/js/main-header.js
  src/js/sub-header.js
Labels: 🐞버그수정

#211 🐛 bug : 메뉴 닫힘현상 설정
  src/components/main-header.html
  src/js/main-header.js
  src/js/sub-header.js
Labels: 🐞버그수정

#212 Shop menu psy
  src/components/main-header.html
  src/js/main-header.js
  src/js/sub-header.js
  src/pages/shop-hotnkit.html
  src/pages/shop-shrimp.html
Labels: 🐞버그수정

#213 ♻️refactor: components 전체 페이지 수정
  src/components/community-event_item.html
  src/components/community-napolimatfia-buynow.html
  src/components/community-napolimatfia-hashtag.html
  src/components/community-recipes_item.html
  src/components/community-review_all.html
  src/components/community-review_img.html
  src/components/community-review_item.html
  src/components/community-review_text.html
  src/components/join-login-input-component.html
  src/components/main-footer.html
  src/components/main-photoframe.html
  src/components/main-showcase.html
  src/components/pages-btn.html
  src/components/pages-pagination.html
  src/components/pages-pagination2.html
  src/components/pages-rollingtext.html
  src/components/pages-searchbar.html
  src/components/pages-select.html
  src/components/pages-summary.html
  src/components/pages-tag.html
  src/components/pages-text.html
  src/components/shop-component_info.html
  src/components/shop-component_taste.html
  src/components/shop-product_item.html
  src/components/shop-product_item2.html
  src/components/shop-product_item3.html
  src/components/shop-section01.html
  src/components/shop-section02.html
  src/components/shop-section03.html
  src/components/shop-section04.html
  src/components/shop-section05.html
  src/components/shop-section06.html
  src/components/shop-section07.html
  src/components/shop-section08.html
  src/components/shop-section09.html
  src/components/shop-section10.html
  src/components/shop-section11.html
  src/components/shop-section12.html
  src/components/shop-section13.html
Labels: 🐞버그수정, 🛠️코드수정

#215 🐛 bug : animation끊김현상조정
  src/pages/shop-parmesan.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
  src/style.css
Labels: 🐞버그수정

#217 💄Review/script -swiper
  index.html
  src/main.js
  src/pages/community-review.html
  src/pages/index_2.html
  src/pages/shop-parmesan.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
Labels: 🐞버그수정, ✨ 기능개발, 🎨코드구현

#218 :recycle: refactor: modal 제작 및 추가 / 컴포넌트 페이지들 리팩토링
  index.html
  src/components/community-event_item.html
  src/components/community-napolimatfia-buynow.html
  src/components/community-napolimatfia-hashtag.html
  src/components/community-recipes_item.html
  src/components/community-review_all.html
  src/components/community-review_img.html
  src/components/community-review_item.html
  src/components/community-review_text.html
  src/components/join-login-input-component.html
  src/components/main-footer.html
  src/components/main-header.html
  src/components/main-photoframe.html
  src/components/main-showcase.html
  src/components/modal.html
  src/components/pages-btn.html
  src/components/pages-pagination.html
  src/components/pages-pagination2.html
  src/components/pages-rollingtext.html
  src/components/pages-searchbar.html
  src/components/pages-select.html
  src/components/pages-summary.html
  src/components/pages-tag.html
  src/components/pages-text.html
  src/components/shop-component_info.html
  src/components/shop-component_taste.html
  src/components/shop-product_item.html
  src/components/shop-product_item2.html
  src/components/shop-product_item3.html
  src/components/shop-section01.html
  src/components/shop-section02.html
  src/components/shop-section03.html
  src/components/shop-section04.html
  src/components/shop-section05.html
  src/components/shop-section06.html
  src/components/shop-section07.html
  src/components/shop-section08.html
  src/components/shop-section09.html
  src/components/shop-section10.html
  src/components/shop-section11.html
  src/components/shop-section12.html
  src/components/shop-section13.html
  src/js/main-header.js
  src/js/modal.js
  src/js/sub-header.js
  src/main.js
  src/pages/home.html
  src/style.css
Labels: ✨ 기능개발, 🛠️코드수정

#219 :lipstick:style: showcase-popup 컴포넌트 제작
  public/assets/images/popup-bg.jpg
  public/assets/images/showcase-popup-parmesan-MO.png
  public/assets/images/showcase-popup-parmesan.png
  public/assets/images/showcase-popup-pyogo-MO.png
  public/assets/images/showcase-popup-pyogo.png
  public/assets/images/showcase-popup-shrimp-MO.png
  public/assets/images/showcase-popup-shrimp.png
  src/components/showcase-parmesan-popup.html
  src/components/showcase-pyogo-popup.html
  src/components/showcase-shrimp-popup.html
  src/style.css
Labels: 🎨코드구현

#221 💄style : js파일 수정
  index.html
  src/js/index.js
  src/js/review-slide.js
  src/main.js
  src/pages/community-review.html
Labels: 🎨코드구현

#223 :lipstick:style: 메인 페이지 컴포넌트 팝업 링크 연결
  src/pages/home.html
Labels: 🎨코드구현

#225 ♻️ refactor : 코드추가수정
  src/components/showcase-parmesan-popup.html
  src/components/showcase-pyogo-popup.html
  src/components/showcase-shrimp-popup.html
Labels: 🛠️코드수정

#233 :recycle:refactor: 인덱스 페이지 멤버소개 깃헙 링크 수정
  index.html
Labels: 🛠️코드수정

#235 :recycle:refactor: 인덱스 코드 리펙토링
  src/pages/about-inquiry.html
Labels: 🛠️코드수정

#236 :recycle: refactor: page repactor
  index.html
  src/components/modal.html
  src/components/showcase-parmesan-popup.html
  src/components/showcase-pyogo-popup.html
  src/components/showcase-shrimp-popup.html
  src/pages/home.html
Labels: 🛠️코드수정

#238 ♻️refactor : validate-html
  README.md
  index.html
  public/assets/icon/first.svg
  public/assets/icon/last.svg
  public/assets/icon/next.svg
  public/assets/icon/previous.svg
  public/assets/images/sec8-graph_1.png
  src/components/main-header.html
  src/components/pages-btn.html
  src/components/pages-pagination.html
  src/components/pages-pagination2.html
  src/components/pages-searchbar.html
  src/components/pages-summary.html
  src/components/shop-component_info.html
  src/components/shop-product_item2.html
  src/components/shop-product_item3.html
  src/js/main-header.js
  src/js/sub-header.js
  src/pages/community-event.html
  src/pages/community-eventboard.html
  src/pages/community-faq.html
  src/pages/community-recipes_and_paring.html
  src/pages/community-review.html
  src/pages/home.html
  src/pages/search.html
  src/pages/shop-giftbag.html
  src/pages/shop-hotnkit.html
  src/pages/shop-parmesan.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
Labels: 🖥️웹접근성, 🛠️코드수정

#242 :recycle:refactor: event 코드 리펙토링
  public/assets/images/event-con-1.jpg
  public/assets/images/event-con-2.jpg
  public/assets/images/event-visual.jpg
  src/pages/community-event.html
Labels: 🛠️코드수정

#239 Validate to HTML
  README.md
  index.html
  public/assets/icon/first.svg
  public/assets/icon/last.svg
  public/assets/icon/next.svg
  public/assets/icon/previous.svg
  public/assets/images/event-con-1.jpg
  public/assets/images/event-con-2.jpg
  public/assets/images/event-visual.jpg
  public/assets/images/sec8-graph_1.png
  src/components/main-header.html
  src/components/modal.html
  src/components/pages-btn.html
  src/components/pages-pagination.html
  src/components/pages-pagination2.html
  src/components/pages-searchbar.html
  src/components/pages-summary.html
  src/components/shop-component_info.html
  src/components/shop-product_item2.html
  src/components/shop-product_item3.html
  src/components/showcase-parmesan-popup.html
  src/components/showcase-pyogo-popup.html
  src/components/showcase-shrimp-popup.html
  src/js/main-header.js
  src/js/sub-header.js
  src/pages/about-inquiry.html
  src/pages/community-event.html
  src/pages/community-eventboard.html
  src/pages/community-faq.html
  src/pages/community-recipes_and_paring.html
  src/pages/community-review.html
  src/pages/home.html
  src/pages/search.html
  src/pages/shop-giftbag.html
  src/pages/shop-hotnkit.html
  src/pages/shop-parmesan.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
Labels: 🌍배포

#248 ♻️refactor : home-refactor
  public/assets/images/left-showcase.png
  public/assets/images/right-showcase.png
  src/components/main-footer.html
  src/components/main-header.html
  src/js/footer.js
  src/js/main-header.js
  src/js/sub-header.js
  src/pages/home.html
Labels: 🛠️코드수정

#249 ♻️refactor : index-html
  index.html
  public/assets/images/component-1.png
  public/assets/images/component-10.png
  public/assets/images/component-11.png
  public/assets/images/component-12.png
  public/assets/images/component-2.png
  public/assets/images/component-3.png
  public/assets/images/component-4.png
  public/assets/images/component-5.png
  public/assets/images/component-6.png
  public/assets/images/component-7.png
  public/assets/images/component-8.png
  public/assets/images/component-9.png
  public/assets/images/computer.png
  public/assets/images/phone.png
  public/assets/images/product-1.png
  public/assets/images/product-2.png
  public/assets/images/product-3.png
  public/assets/images/product-all.png
Labels: 🛠️코드수정

#247 :recycle:refactor: about ourbrand 코드 리펙토링
  public/assets/images/main-frame1.png
  public/assets/images/main-logo.png
  public/assets/images/main.jpg
  public/assets/images/main01-zip.jpg
  public/assets/images/main02-zip.jpg
  public/assets/images/main02.jpg
  public/assets/images/main03-zip.jpg
  public/assets/images/main04-zip.jpg
  public/assets/images/main05-zip.jpg
  public/assets/images/main06-zip.jpg
  public/assets/images/main07-zip.jpg
  public/assets/images/main1.jpg
  src/pages/about-ourbrand.html
Labels: 🛠️코드수정

#257 :recycle:refactor 커뮤니티 FAQ . QNA 타이틀 수정
  public/assets/images/qna-phone.png
  src/pages/community-faq.html
  src/pages/community-qna.html
Labels: 🛠️코드수정

#256 ♻️refactor : home/header refactor
  src/components/main-header.html
  src/js/main-header.js
  src/js/sub-header.js
  src/pages/home.html
Labels: 🛠️코드수정

#255 ♻️refactor : recipes/review-html
  public/assets/images/recipes-1.jpg
  public/assets/images/recipes-2.jpg
  public/assets/images/recipes-3.jpg
  public/assets/images/recipes-4.jpg
  public/assets/images/recipes-5.jpg
  public/assets/images/recipes-6.jpg
  public/assets/images/recipes-7.jpg
  public/assets/images/recipes-8.jpg
  public/assets/images/review-1.jpg
  public/assets/images/review-10.jpg
  public/assets/images/review-11.jpg
  public/assets/images/review-12.jpg
  public/assets/images/review-13.jpg
  public/assets/images/review-14.jpg
  public/assets/images/review-15.png
  public/assets/images/review-16.jpg
  public/assets/images/review-17.jpg
  public/assets/images/review-18.jpg
  public/assets/images/review-19.jpg
  public/assets/images/review-2.jpg
  public/assets/images/review-20.png
  public/assets/images/review-21.png
  public/assets/images/review-22.png
  public/assets/images/review-23.jpg
  public/assets/images/review-24.jpg
  public/assets/images/review-25.jpg
  public/assets/images/review-26.jpg
  public/assets/images/review-27.jpg
  public/assets/images/review-3.jpg
  public/assets/images/review-4.jpg
  public/assets/images/review-5.jpg
  public/assets/images/review-6.jpg
  public/assets/images/review-7.jpg
  public/assets/images/review-8.jpg
  public/assets/images/review-9.jpg
  public/assets/images/review-con-1.jpg
  public/assets/images/review-con-1.png
  public/assets/images/review-con-2.jpg
  public/assets/images/review-con-3.jpg
  public/assets/images/review-con-4.jpg
  public/assets/images/review-con-5.jpg
  src/pages/community-recipes_and_paring.html
  src/pages/community-review.html
Labels: 🛠️코드수정

#260 shop-hotnkit-psy
  public/assets/images/product-all.png
  src/pages/shop-hotnkit.html
Labels: 🛠️코드수정

#262 ♻️refactor : shop-refactor
  public/assets/images/product-all.png
  src/pages/shop-parmesan.html
  src/pages/shop-shrimp.html
Labels: 🎨코드구현

#261 :recycle:refactor: 나폴리 맛피아 코드 리펙토링
  public/assets/images/intro-1.jpg
  src/components/community-napolimatfia-buynow.html
  src/components/community-napolimatfia-hashtag.html
  src/pages/community-napolimatfia.html
Labels: 🛠️코드수정

#263 ♻️ refactor : allpages
  src/components/community-event_item.html
  src/components/community-recipes_item.html
  src/components/community-review_all.html
  src/components/community-review_img.html
  src/components/community-review_item.html
  src/components/community-review_text.html
  src/components/join-login-input-component.html
  src/components/main-footer.html
  src/components/main-header.html
  src/components/main-photoframe.html
  src/components/main-showcase.html
  src/components/modal.html
  src/components/pages-btn.html
  src/components/pages-pagination.html
  src/components/pages-pagination2.html
  src/components/pages-rollingtext.html
  src/components/pages-searchbar.html
  src/components/pages-select.html
  src/components/pages-summary.html
  src/components/pages-tag.html
  src/components/pages-text.html
  src/components/shop-component_info.html
  src/components/shop-component_taste.html
  src/components/shop-product_item.html
  src/components/shop-product_item2.html
  src/components/shop-product_item3.html
  src/components/showcase-parmesan-popup.html
  src/components/showcase-pyogo-popup.html
  src/components/showcase-shrimp-popup.html
  src/pages/about-ourbrand.html
  src/pages/community-event.html
  src/pages/community-eventboard.html
  src/pages/community-faq.html
  src/pages/community-napolimatfia.html
  src/pages/community-review.html
  src/pages/join-login.html
  src/pages/search.html
  src/pages/shop-all_products.html
  src/pages/shop-giftbag.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
Labels: 🖥️웹접근성, 🛠️코드수정

#265 :recycle:refactor shop 이미지 w값 리펙토링
  src/pages/shop-giftbag.html
  src/pages/shop-hotnkit.html
  src/pages/shop-parmesan.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
Labels: 🛠️코드수정

#267 ♻️ refactor : preload
  src/pages/home.html
Labels: 🖥️웹접근성, 🛠️코드수정

#268 :recycle: refactor: main image 수정
  public/assets/images/main01-zip.jpg
  public/assets/images/main02-zip.jpg
  public/assets/images/main03-zip.jpg
  public/assets/images/main04-zip.jpg
  public/assets/images/main05-zip.jpg
  public/assets/images/main06-zip.jpg
  public/assets/images/main07-zip.jpg
Labels: 🛠️코드수정

#269 🚀main : code update
  public/assets/images/main01-zip.jpg
  public/assets/images/main02-zip.jpg
  public/assets/images/main03-zip.jpg
  public/assets/images/main04-zip.jpg
  public/assets/images/main05-zip.jpg
  public/assets/images/main06-zip.jpg
  public/assets/images/main07-zip.jpg
  src/pages/home.html
  src/pages/shop-giftbag.html
  src/pages/shop-hotnkit.html
  src/pages/shop-parmesan.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
Labels: 🌍배포

#271 🖥️ accessibility: index.html edit
  index.html
  src/js/index.js
  src/style.css
Labels: 🖥️웹접근성, 🛠️코드수정

#272 ♻️Refactor/index home psy
  index.html
  src/components/main-footer.html
  src/components/main-header.html
  src/js/footer.js
  src/js/main-header.js
  src/js/sub-header.js
  src/pages/home.html
Labels: 🖥️웹접근성, 🛠️코드수정

#279 ✨ feat : Animate reduce/psy
  index.html
  src/components/main-showcase.html
  src/components/pages-rollingtext.html
  src/components/shop-section04.html
  src/components/shop-section06.html
  src/components/showcase-parmesan-popup.html
  src/components/showcase-pyogo-popup.html
  src/components/showcase-shrimp-popup.html
  src/pages/cart.html
  src/pages/community-event.html
  src/pages/community-napolimatfia.html
  src/pages/home.html
  src/pages/shop-giftbag.html
  src/pages/shop-hotnkit.html
  src/pages/shop-parmesan.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
Labels: 🖥️웹접근성, ✨ 기능개발

#280 🚀 depoly : main update
  index.html
  src/components/main-showcase.html
  src/components/pages-rollingtext.html
  src/components/shop-section04.html
  src/components/shop-section06.html
  src/components/showcase-parmesan-popup.html
  src/components/showcase-pyogo-popup.html
  src/components/showcase-shrimp-popup.html
  src/pages/cart.html
  src/pages/community-event.html
  src/pages/community-napolimatfia.html
  src/pages/home.html
  src/pages/shop-giftbag.html
  src/pages/shop-hotnkit.html
  src/pages/shop-parmesan.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
Labels: 🌍배포

#281 🐛 bug : motion-reduce edit
  index.html
  src/components/community-napolimatfia-hashtag.html
  src/components/main-showcase.html
  src/components/pages-rollingtext.html
  src/components/shop-section04.html
  src/components/shop-section06.html
  src/components/showcase-parmesan-popup.html
  src/components/showcase-pyogo-popup.html
  src/components/showcase-shrimp-popup.html
  src/pages/cart.html
  src/pages/community-event.html
  src/pages/community-napolimatfia.html
  src/pages/home.html
  src/pages/shop-giftbag.html
  src/pages/shop-hotnkit.html
  src/pages/shop-parmesan.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
Labels: 🐞버그수정

#282 🚀 depoly : main update
  index.html
  src/components/community-napolimatfia-hashtag.html
  src/components/main-showcase.html
  src/components/pages-rollingtext.html
  src/components/shop-section04.html
  src/components/shop-section06.html
  src/components/showcase-parmesan-popup.html
  src/components/showcase-pyogo-popup.html
  src/components/showcase-shrimp-popup.html
  src/pages/cart.html
  src/pages/community-event.html
  src/pages/community-napolimatfia.html
  src/pages/home.html
  src/pages/shop-giftbag.html
  src/pages/shop-hotnkit.html
  src/pages/shop-parmesan.html
  src/pages/shop-pyogo.html
  src/pages/shop-shrimp.html
Labels: 🌍배포
